ServerName localhost

<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /app/public

    <Directory /app/public>
        AllowOverride All
        Require all granted
        Options FollowSymLinks
    </Directory>

    <IfModule mod_headers.c>
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set Referrer-Policy "strict-origin-when-cross-origin"
    </IfModule>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
